###########################################################
### Welcome to Beautiful Jekyll!
### This config file is configured for a non-blog website.
###########################################################

############################
# --- Required options --- #
############################

# Name of website
title: My ada website

# Your name to show in the footer
author: ImportNumpyAsPd

###############################################
# --- List of links in the navigation bar --- #
###############################################

navbar-links:
  Home: "index"
  About Me: "aboutme"
  Contact: "contact"

################
# --- Logo --- #
################

# Image to show in the navigation bar - works best with a square image
avatar: "/assets/img/avatar-icon.png"
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

social-network-links:
  email: "someone@example.com"
  github: daattali
  twitter: daattali

###########################
# --- General options --- #
###########################

# Remove blog-related settings
paginate: 0  # No blog posts
permalink: /:title/  # Clean URLs

# Remove unnecessary feed features
feed_show_excerpt: false
feed_show_tags: false

# Enable custom CSS if needed
site-css:
  - "/assets/css/custom-styles.css"

#####################################
# --- Colours / Background Image --- #
#####################################

# Colours for the website
page-col: "#FFFFFF"
text-col: "#404040"
link-col: "#008AFF"
hover-col: "#0085A1"
navbar-col: "#EAEAEA"
navbar-text-col: "#404040"
footer-col: "#EAEAEA"
footer-text-col: "#777777"

#####################################
# --- Plugins and Excludes --- #
#####################################

exclude:
  - README.md
  - CHANGELOG.md

plugins:
  - jekyll-sitemap
